spring:
  cloud:
    config:
      server:
        native:
          search-locations: 'file:${config.path}'
  profiles:
    active: 'native'
  application:
    name: 'config-server'
server:
  port: 8061
